version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'blog'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network

volumes:
  mysql_data:

networks:
  network: